pool:
  vmImage: 'Ubuntu 16.04'

steps:
- script: yarn install
- script: yarn run lint
- script: yarn run build
  env:
    CONTENTFUL_SPACE_ID: $(CONTENTFUL_SPACE_ID)
    CONTENTFUL_DELIVERY_TOKEN: $(CONTENTFUL_DELIVERY_TOKEN)

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/public'
    includeRootFolder: false

- task: AzureRmWebAppDeployment@3
  inputs:
    azureSubscription: 'Personal'
    WebAppName: 'chadstatic'
    Package: $(System.ArtifactsDirectory)/**/*.zip