pool:
  vmImage: 'Ubuntu 16.04'

steps:
- script: yarn install
- script: yarn run lint
- script: yarn run build
  env:
    CONTENTFUL_SPACE_ID: $(CONTENTFUL_SPACE_ID)
    CONTENTFUL_DELIVERY_TOKEN: $(CONTENTFUL_DELIVERY_TOKEN)